Repository eAmod/eAmod, pull requests merged in 2018-09, with the labels that each got.

#94 [shellTeMP] [ADD] Race of the Day System 09/12/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_race_of_the_day_system.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_race_of_the_day_system.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_race_of_the_day_system.txt
Labels: code review: Accepted, component review: Accepted, component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Work to be done

#96 [shellTeMP] [ADD] & [MOVE] Race of the Day System 09/14/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.3.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v1.0.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.3.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v1.0.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.3.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v1.0.txt
Labels: code review: Accepted, component review: Accepted, component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Work to be done

#97 [shellTeMP] [ADD] Race of the Day System v3.4 09/18/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.4.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.4.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v.3.4.txt
Labels: code review: Accepted, component review: Accepted, component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Confirmed, type: Work to be done

#101 [shellTeMP] [ADD], [UPDATE] & [FIXES] GM Safe v1.3 09/25/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.0.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.3.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.3.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.4.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.0.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.3.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.3.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.4.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_ban_system.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.0.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/GMSafe/eAmod_gmsafe_v1.3.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.3.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/ROTD/eAmod_race_of_the_day_system_v3.4.txt
Labels: code review: Accepted, component review: Accepted, component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Confirmed, type: Enhancement, type: Work to be done

#102 [J3MK1] [ADD] Floating Rate System 09/27/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_floating_rate_system_v1.2.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_floating_rate_system_v1.2.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_floating_rate_system_v1.2.txt
Labels: component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Code Review, type: Enhancement, type: Work to be done
