Repository eAmod/eAmod, pull requests merged in 2018-08, with the labels that each got.

#76 [J3MK1] [ADD] NPC Announcer 08/06/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
Labels: component: Scripts, mode: Pre-Renewal, status: Needs analysis from GRAVITY CEO

#79 [shellTeMP] [ADD] Game Master Safe 08/07/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
Labels: component: Scripts, status: Confirmed by GRAVITY CEO, type: Work to be done

#80 [J3MK1] [ADD] [FIX] eAmod Support All Maps & NPC Announcer 08/06/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
Labels: component: Scripts, mode: Pre-Renewal, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Work to be done

#81 [shellTeMP] [FIX] Credits 08/07/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_ban_system.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_ban_Ssystem.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_announcer_lvl.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_ban_system.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_gmsafe.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_support_all_maps.txt
Labels: component: Scripts, mode: Pre-Renewal, mode: Renewal, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Work to be done

#82 [shellTeMP] [FIX] Credits 08/07/2018
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_nodropvending.txt
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_nodropvending.txt
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/npc-addons/custom/eAmod/English/eAmod_nodropvending.txt
Labels: component: Documentation, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Work to be done

#83 [shellTeMP] [ADD], [UPDATE] Loot a Lot System 12/07/2018
  Documentations/Costumer/Downloads/eAmod_Costumer-downloads_EN-US.txt
  Documentations/Costumer/Downloads/eAmod_Costumer-downloads_JP.txt
  Documentations/Costumer/Downloads/eAmod_Costumer-downloads_PT-BR.txt
  Documentations/Costumer/Loot a Lot/eAmod_Costumer-Lootaloot_EN-US.txt
  Documentations/Costumer/Loot a Lot/eAmod_Costumer-Lootaloot_PT-BR.txt
  Documentations/Costumer/SQL Files/eAmod_Costumer-sql-files_PT-BR.txt
  Documentations/Staff/Headers/Source/eAmod_Src_Header_EN-UStxt
  Documentations/Staff/Headers/Source/eAmod_Src_Header_PT-BR.txt
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/conf-addons/battle/items.conf
  Servers/eAmob-A Rev-471/Addons Rev-471/Server Side/eAmod-addons/src-addons/plugins/@lootalot.c
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/conf-addons/battle/items.conf
  Servers/eAmob-B Rev-304/Addons Rev-304/Server Side/eAmod-addons/src-addons/plugins/@lootalot.c
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/conf-addons/battle/items.conf
  Servers/eAmob-C Rev-502/Addons Rev-502/Server Side/eAmod-addons/src-addons/plugins/@lootalot.c
Labels: component: Documentation, component: Source, mode: Pre-Renewal, mode: Renewal, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Work to be done

#84 [shellTeMP] [UDATE] Header 12/07/2018
  Documentations/Costumer/SQL Files/eAmod_Costumer-sql-files_EN-US.txt
Labels: component: Documentation, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Work to be done

#86 [shellTeMP] [UDATE] Header 12/07/2018
  Documentations/Staff/Headers/Source/eAmod_Src_Header_EN-UStxt
  Documentations/Staff/Headers/Source/eAmod_Src_Header_PT-BR.txt
Labels: component: Documentation, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Work to be done

#87 [Freya] [UDATE] Header 12/07/2018
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/char.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/char.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_guild.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_guild.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_homun.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_homun.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_party.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_party.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_pet.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_pet.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_status.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_status.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_storage.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_storage.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/inter.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/inter.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/char.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/char.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_achievement.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_achievement.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_auction.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_auction.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_elemental.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_elemental.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_guild.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_guild.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_homun.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_homun.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mail.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mail.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mercenary.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mercenary.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_party.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_party.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_pet.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_pet.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_quest.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_quest.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_storage.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_storage.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/inter.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/inter.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/cbasetypes.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/core.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/core.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/db.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/db.h
Labels: component: Source, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Help Wanted, type: Work to be done

#89 [shellTeMP] [UDATE] Header 12/07/2018
  Documentations/Staff/Headers/Source/eAmod_Src_Header_EN-UStxt
  Documentations/Staff/Headers/Source/eAmod_Src_Header_PT-BR.txt
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/char.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/char.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_guild.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_guild.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_homun.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_homun.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_party.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_party.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_pet.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_pet.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_status.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_status.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_storage.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/int_storage.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/inter.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char/inter.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/char.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/char.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_achievement.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_achievement.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_auction.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_auction.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_elemental.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_elemental.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_guild.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_guild.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_homun.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_homun.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mail.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mail.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mercenary.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_mercenary.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_party.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_party.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_pet.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_pet.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_quest.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_quest.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_storage.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/int_storage.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/inter.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/char_sql/inter.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/cbasetypes.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/core.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/core.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/db.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/db.h
Labels: component: Documentation, component: Source, status: Confirmed, status: Confirmed by GRAVITY CEO, type: Enhancement, type: Work to be done

#90 [shellTeMP] [UPDATE] Header 08/13/2018
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/des.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/des.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/ers.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/ers.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/grfio.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/grfio.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/lock.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/lock.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/malloc.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/malloc.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/mapindex.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/mapindex.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/md5calc.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/md5calc.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/mmo.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/nullpo.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/nullpo.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/plugin.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/plugins.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/plugins.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/random.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/random.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/showmsg.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/showmsg.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/socket.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/socket.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/sql.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/sql.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/strlib.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/strlib.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/timer.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/timer.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/utils.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/utils.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/common/version.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/plugins/console.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/plugins/dbghelpplug.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/plugins/pid.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/plugins/sample.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/plugins/sig.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/tool/mapcache.c
  Servers/eAmob-C Rev-502/eAthena (Classic) (Trunk)/src/txt-converter/char-converter.c
  Servers/eAmob-C Rev-502/eAthena (Classic) (Trunk)/src/txt-converter/login-converter.c
Labels: component: Source, status: Needs analysis from GRAVITY CEO, type: Enhancement, type: Work to be done

#91 [J3MK1] [UPDATE] Header eAthena (3CeAM) 08/13/2018
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/account.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/account_sql.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/account_txt.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/ipban.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/ipban_sql.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/ipban_txt.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/login.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/login.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/loginlog.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/loginlog_sql.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/login/loginlog_txt.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/achievement.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/achievement.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/atcommand.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/atcommand.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/battle.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/battle.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/battleground.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/battleground.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/buyingstore.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/buyingstore.h
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/channel.c
  Servers/eAmob-A Rev-471/eAthena (3CeAM) (Trunk)/src/map/channel.h
Labels: component: Documentation, status: Needs analysis from GRAVITY CEO, type: Work to be done
